metadata:
  rank: int

data:
  temperatures:
    type: array
    subtype: double
    size: [32, 32]

plugins:
  # trace: ~
  pycall:
    on_event:
      init:
        with: {rank: $rank}
        exec: |
          from doreisa.simulation_node import Client
          client = Client()
          client.create_array("temperatures", (3, 3), (rank % 3, rank // 3))

      simulation_step:
        with: {temperatures: $temperatures}
        exec: |
          client.simulation_step([temperatures])
