metadata:
  rank: int

data:
  temperatures:
    type: array
    subtype: double
    size: [12, 12]

plugins:
  # trace: ~
  pycall:
    on_event:
      init:
        with: {rank: $rank}
        exec: |
          from doreisa.simulation_node import Client
          client = Client(rank)

      simulation_step:
        with: {temperatures: $temperatures}
        exec: |
          client.simulation_step(temperatures)
