metadata:
  rank: int

data:
  temperatures:
    type: array
    subtype: double
    size: [32, 32]

plugins:
  # trace: ~
  pycall:
    on_event:
      init:
        with: {rank: $rank}
        exec: |
          from doreisa.simulation_node import Client
          client = Client(rank)

      simulation_step:
        with: {temperatures: $temperatures}
        exec: |
          client.add_chunk("temperatures", (rank // 3, rank % 3), temperatures, store_externally=False)
