metadata:
  rank: int

data:
  temperatures:
    type: array
    subtype: double
    size: [3002, 3002]

plugins:
  # trace: ~
  pycall:
    on_event:
      init:
        with: {rank: $rank}
        exec: |
          from doreisa.simulation_node import Client
          client = Client(rank)

      simulation_step:
        with: {temperatures: $temperatures}
        exec: |
          client.add_chunk("temperatures", (rank // 2, rank % 2), (2, 2), temperatures, store_externally=False)
